### ISSUE TITLE
Add profiles to be able to compile native code either by cross-compiler or local (on-board) compiler

### ISSUE THREAD

**Issue by pmacik** [px3/bulldog#20]
e.g. for CubieBoard:
Crosscompiler:
<compiler.exec>arm-linux-gnu-gcc</compiler.exec>
<compilerStartOption>-std=gnu11 -O3 -fPIC -fgnu89-inline -mfloat-abi=hard -mlittle-endian -DARM -DARCH="ARM" -marm -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=vfpv4-d16 -mfpu=neon-vfpv4 -funsafe-math-optimizations</compilerStartOption>
<linker.exec>arm-linux-gnu-ld</linker.exec>

Local compiler:
<compiler.exec>gcc</compiler.exec>
<compilerStartOption>-std=gnu11 -O3 -fPIC -mfloat-abi=hard -mlittle-endian -DARM -DARCH="ARM" -marm</compilerStartOption>
<linker.exec>ld</linker.exec>

**Comment by sbunciak** [comment]
Profile added in https://github.com/px3/bulldog/commit/4dd91d61936a431501e7e28fc0f1bdd1a477d003
