### ISSUE TITLE
Please push snapshots to Sonatype

### ISSUE THREAD

**Issue by timmolter** [px3/bulldog#39]
At https://oss.sonatype.org/content/groups/public/io/silverspoon/bulldog-board-beagleboneblack/, I would expect to see version 0.2.0-SNAPSHOT, but it's not there.

You can integrate Travis CI into your repo quite easily to automatically build and push snapshots to Sonatype. 

http://knowm.org/configure-travis-ci-to-deploy-snapshots/

For now I'll install the jars locally.

**Comment by sbunciak** [comment]
Hi, thanks for pointing this out! 
I'll try to set it up later this week.

**Comment by sbunciak** [comment]
Fixed in https://github.com/px3/bulldog/commit/bb4ccc274c366b214e97bac483a696faa8697ea5
