### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by max90727** [px3/bulldog#54]
Hi:
Thanks for the library and I am trying use the library on BeagleBone Black.
I got the error ArrayIndexOutOfBoundsException: 0 in Platform.createBoard(). 
My OS is Ubuntu. 
I installed the library with Maven, and copy the jars and the .so into my project folder, then compiled with ant. Running with java commands.
Please help me.

**Comment by xjaros1** [comment]
Hello, are you using bulldog on debian 8.0 Jessie?
This OS is currently unsupported due to changes in interface of peripherials.
If you want to resolve this, try to run bulldog on latest image[1]

[1] http://debian.beagleboard.org/images/bone-debian-7.8-lxde-4gb-armhf-2015-03-01-4gb.img.xz

**Comment by max90727** [comment]
Thanks for the quick reply. I will try that.

**Comment by max90727** [comment]
it works now, thanks
