### ISSUE TITLE
How to read digital input signal

### ISSUE THREAD

**Issue by max90727** [px3/bulldog#55]
Hi. I write some code for reading the digital input, but I got the error as "could not create pin". Please help me.
                Board board = Platform.createBoard();
		DigitalInput digitalInput=board.getPin(BBBNames.P8_12).as(DigitalInput.class);
		Signal signal=digitalInput.read();
		System.out.println(signal.getNumericValue());

**Comment by xjaros1** [comment]
Hello, are you running your code as root? Are there any exceptions printed?

**Comment by pmacik** [comment]
Hi max90727, I fixed the code that most likely caused your issue. Can you please try your code now and confirm it works for you?

Thanks!

**Comment by max90727** [comment]
Thanks for your help. My project goes fine now, and I found that I can read the signal from my temperature sensor by building the device tree. Anyway, still thanks for your help and I will try that when I have more time.
