### ISSUE TITLE
How to use DS18B20TemperatureSensor

### ISSUE THREAD

**Issue by max90727** [px3/bulldog#56]
Hi. I found the class DS18B20TemperatureSensor in your library but I am confuse about the input parameter "File deviceFile", could you tell me what kind file it is? Thanks.

**Comment by sbunciak** [comment]
Hi, that's meant to be the sensor-specific directory created by w1 kernel module. Default path  is ```/sys/bus/w1/devices/28-xxx```. You might want to check https://learn.adafruit.com/adafruits-raspberry-pi-lesson-11-ds18b20-temperature-sensing/ds18b20

**Comment by max90727** [comment]
Thanks for you reply. I was going to tell you I found the solution.
