### ISSUE TITLE
Required documentation on io.silverspoon.bulldog.raspberrypi.RaspiNames constants.

### ISSUE THREAD

**Issue by yangboz** [px3/bulldog#59]
For example, Which name was matched to "Respberry Pi Model B+ V1.2" ?

**Comment by xjaros1** [comment]
I don't understand the question. In RaspiNames are constants for pins only. Detection of platform is done automatically. Device layout is same for RaspberryPi A, B+ and 2, so there is no need for platform specific names if that's what you are asking for.

**Comment by yangboz** [comment]
Let me re-clarify the question. According to example code at https://github.com/px3/bulldog
'''
//Set up a digital output
    DigitalOutput output = board.getPin(RaspiNames.P1_11).as(DigitalOutput.class);
'''
My question is: as a beginner I don't know  which constant parameter is suitable for  "board.getPin()", while I am using "Respberry Pi Model B+ V1.2" board?

Thanks,
Yangbo

**Comment by xjaros1** [comment]
Ok that doesn't depend on board but on pin you want to use. I would recommend you to read this: 

http://elinux.org/RPi_Low-level_peripherals

Here are described pins on Raspberry PI and what are capabilities of those pins.

**Comment by xjaros1** [comment]
I'm closing this issue.
