### ISSUE TITLE
Examples for USR0-3 LEDs

### ISSUE THREAD

**Issue by benedekh** [px3/bulldog#79]
Dear All,

Do you have any examples, how to use the onboard USR0-3 LEDs with the bulldog lib on Debian Jessie?

I found [bulldog-examples](https://github.com/px3/bulldog-examples) but it does not include any that would make these LEDs work. (The board works perfectly by the way.)

Thank you for help.

**Comment by xjaros1** [comment]
USR0-3 are controlled by GPIO1_{21,24} which are currently not supported by bulldog. 
You can track progress in here #80
