### ISSUE TITLE
Just a documentation request

### ISSUE THREAD

**Issue by nrapopor** [px3/bulldog#90]
@mijaros ...

Hi Miroslav,

First of all thanks for an awesome library.  Please take pity on us n00bs and change the README to mention the requirement to run the code as root -- my code was failing quite spectacularly, and I was blaming everything under the sun (or more accurately under ubuntu/debian, thinking I had an old soft float image, conflicting library, etc) until I found your comment to that effect. 

Thanks,

Nick

**Comment by mijaros** [comment]
Hi,
here it is: 2ae0bf76065b2870a092538c67f62d9811559d27
